### ISSUE TITLE
Update extension name to be in line with the other RH extensions

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-yeoman#12]
Instead of simply "yo" as it is listed right now, we should probably change the description of this extension to be more in line with the others... Perhaps "Yeoman Support by Red Hat" would be a better extension name.

**Comment by bfitzpat** [comment]
Should probably also update the keywords so the extension is easier to find. Right now it overlaps with the older "Yo" extension

**Comment by apupier** [comment]
> Right now it overlaps with the older "Yo" extension

I think it is great to overlap with the older one so that people searching for the older one will find the new one.

**Comment by apupier** [comment]
> Perhaps "Yeoman Support by Red Hat" would be a better extension name.

i think it will make more sense to the repository to be placed in rh-developers github organization to have this name.
On Camel side, we try to be be as open as possible and it is currently in Camel Tooling repository.
But I feel this is question more for Product Managers on how they want to advertize it.

**Comment by gaughan** [comment]
Agree if it is in camel repo, maybe keep open

**Comment by bfitzpat** [comment]
Ok. This is in the camel repo, so I'll leave it for now and we can discuss it down the line again if it comes up. Thanks for the feedback @apupier  and @gaughan
