### ISSUE TITLE
Fix Sonar analysis

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-yeoman#19]
currently failing with:

```
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 29.238s
INFO: Final Memory: 24M/150M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: You must define the following mandatory properties for 'Unknown': sonar.projectKey
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

**Comment by bfitzpat** [comment]
Hey @apupier - if you get a chance, can you add the sonar key to the travis build for yeoman? Would be good to get that extra level of checking just in case.

**Comment by apupier** [comment]
You should have the rights to do it yourself. If not, we can work it through to ensure that you have the correct rights.

and seems there is already a SONAR_TOKEN in Travis:(so maybe an invalid one?)
![Screenshot from 2019-09-25 08-46-45](https://user-images.githubusercontent.com/1105127/65575858-0e8e0e00-df71-11e9-9485-f05acc4654f2.png)

so either an invalid one or a bad configuration of the project.

**Comment by bfitzpat** [comment]
Looking at all of the travis configuration and comparing it to other projects, the only thing I can think is that the SONAR TOKEN is invalid. Where do we create a new one?

**Comment by apupier** [comment]
https://sonarcloud.io/documentation/user-guide/user-token/

**Comment by bfitzpat** [comment]
Ok. I have created a new token, updated the master build, and this is what I'm seeing:

 ```
if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then sonar-scanner; fi
INFO: Scanner configuration file: /home/travis/.sonarscanner/sonar-scanner-3.0.3.778/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 3.0.3.778
INFO: Java 11.0.2 Oracle Corporation (64-bit)
INFO: Linux 4.15.0-1028-gcp amd64
INFO: User cache: /home/travis/.sonar/cache
INFO: SonarQube server 8.0.0
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
INFO: Load global settings
INFO: Load global settings (done) | time=699ms
INFO: Server id: 74E9293D-AWHW8ct9-T_TB3XqouNu
INFO: User cache: /home/travis/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=179ms
INFO: Load/download plugins (done) | time=20911ms
INFO: Loaded core extensions: developer-scanner
INFO: Process project properties
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 27.390s
INFO: Final Memory: 7M/27M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: You must define the following mandatory properties for 'Unknown': sonar.projectKey
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
Skipping a deployment with the script provider because this is not a tagged commit
```

Where is "sonar.projectKey"? Do I need to define that in the travis configuration?

**Comment by apupier** [comment]
there are several ways to define the sonar.projectKey, see https://docs.sonarqube.org/latest/analysis/analysis-parameters/

We are using a specific file for that in most of our projects https://github.com/camel-tooling/camel-language-server/blob/master/sonar-project.properties

**Comment by bfitzpat** [comment]
Fixed! https://sonarcloud.io/dashboard?id=vscode-yeoman

**Comment by djelinek** [comment]
verified with master branch
